"use client";

import { useLocaleLabels } from "@/components/lab/use-locale-labels";

const zh = {
  view3d: "從海上看著它翻身降落的 3D 畫面",
  loading3d: "載入 Starship 模型…",
  no3d: "這個瀏覽器開不了 3D（WebGL）。下面的剖面圖照常顯示高度和速度。",
  who: "誰在開",
  engines: "點幾顆引擎",
  manualEngines: "你飛時用幾顆",
  network: "你教的神經網路",
  teach: "教一個神經網路",
  teaching: "上課中…",
  teachAgain: "重新教一次",
  teachNote: "先讓它照抄自動駕駛，再用 DAgger 糾正它自己飛出來的錯。約十秒。",
  phase: "進度",
  cloning: "照抄階段",
  daggerRound: (n: number) => `DAgger 第 ${n} 輪`,
  samples: "看過的狀態",
  cloningNote: "它已經把自動駕駛的答案背得很像了，但多半還是會摔：一偏離老師走過的路，它就沒見過。",
  daggerNote: "現在換它自己飛，老師在旁邊標註它去過的每個狀態，再重新訓練一次。",
  you: "你來飛",
  autopilot: "內建的自動駕駛",
  learned: "你訓練出來的",
  launch: "放開它",
  again: "再來一次",
  pause: "暫停",
  keys: "空白鍵點火並翻身，← → 擺動引擎，↑ ↓ 控制襟翼",
  touchKeys: "按住中間點火，左右擺動引擎",
  altitude: "高度",
  speed: "速度",
  fuel: "燃料",
  throttle: "推力",
  tilt: "姿態",
  metres: "公尺",
  mps: "公尺／秒",
  percent: "%",
  status: "狀態",
  flying: "下降中",
  landed: "降落成功",
  crashed: "墜毀",
  lost: "飛丟了",
  dry: "燃料用完",
  ready: "準備好了",
  tooFast: "太快",
  offPad: "偏離平台",
  tilted: "太歪",
  train: "訓練一個",
  training: "訓練中…",
  trainNote: "在你的瀏覽器裡用交叉熵方法搜尋十個數字，大約一秒。",
  trainAgain: "重新訓練",
  iteration: "第幾輪",
  landRate: "降落成功率",
  touchdown: "觸地速度",
  fuelLeft: "剩餘燃料",
  gains: "它學到的十個數字",
  gainNames: ["點火高度", "翻身力道", "煞車餘裕", "觸地目標速度", "姿態硬度", "橫向修正", "翻身推力", "翻身點幾顆", "煞車最多幾顆", "追速度的力道"],
  scoreboard: (landed: number, tries: number) => `成功 ${landed} 次 / 試了 ${tries} 次`,
  hoverNote: "一顆引擎的推力範圍（0.90–2.26 MN）剛好跨過自重 1.26 MN，兩顆的最小推力已經是自重的 1.4 倍。所以它先要多少推力，再點得出這個推力的最少顆數——煞車時兩顆，最後幾十公尺一顆。",
};

const en: typeof zh = {
  view3d: "The stage coming down, seen from the sea",
  loading3d: "Loading the ship…",
  no3d: "This browser could not start the 3D view (WebGL). The cutaway below still shows height and speed.",
  who: "Flying",
  engines: "Engines lit",
  manualEngines: "Engines when you fly",
  network: "The network you taught",
  teach: "Teach a network",
  teaching: "In class…",
  teachAgain: "Teach it again",
  teachNote: "First it copies the autopilot, then DAgger corrects the mistakes it makes on its own. About ten seconds.",
  phase: "Stage",
  cloning: "Copying",
  daggerRound: (n: number) => `DAgger round ${n}`,
  samples: "States seen",
  cloningNote: "It has learned the autopilot's answers almost exactly, and it still crashes: one small error takes it somewhere the teacher never went.",
  daggerNote: "Now the student flies while the teacher labels every state it reaches, and it trains again.",
  you: "You",
  autopilot: "The built-in autopilot",
  learned: "The one you trained",
  launch: "Drop it",
  again: "Again",
  pause: "Pause",
  keys: "Space lights the engines and flips, ← → gimbal, ↑ ↓ flaps",
  touchKeys: "Hold the middle to fire, the sides to gimbal",
  altitude: "Altitude",
  speed: "Speed",
  fuel: "Fuel",
  throttle: "Thrust",
  tilt: "Tilt",
  metres: "m",
  mps: "m/s",
  percent: "%",
  status: "Status",
  flying: "Descending",
  landed: "Landed",
  crashed: "Crashed",
  lost: "Lost it",
  dry: "Out of fuel",
  ready: "Ready",
  tooFast: "too fast",
  offPad: "off the pad",
  tilted: "too far over",
  train: "Train one",
  training: "Training…",
  trainNote: "The cross-entropy method searches ten numbers in your browser, in about a second.",
  trainAgain: "Train again",
  iteration: "Round",
  landRate: "Landing rate",
  touchdown: "Touchdown",
  fuelLeft: "Fuel left",
  gains: "The ten numbers it found",
  gainNames: ["Ignition height", "How hard it swings", "Braking margin", "Touchdown speed", "Attitude stiffness", "Sideways correction", "Flip throttle", "Engines for the flip", "Most engines while braking", "Chasing the target speed"],
  scoreboard: (landed: number, tries: number) => `${landed} landed of ${tries}`,
  hoverNote: "One Raptor spans 0.90–2.26 MN, which straddles the ship's 1.26 MN weight; two at their floor are already 1.4 times it. So the pilot asks for a thrust and lights the fewest engines that can deliver it — two to brake, one for the last forty metres.",
};

export const useLabels = () => useLocaleLabels(zh, en);
