"use client";

import { useLocaleLabels } from "@/components/lab/use-locale-labels";

const zh = {
  train: "開始訓練", again: "重新訓練", stop: "停止",
  trainNote: "在你的瀏覽器裡從零訓練，大約三分鐘。可以邊練邊聽，也可以繼續往下讀。",
  loading: "下載 333 首聖詠中…", failed: "資料載入失敗，重新整理再試一次。",
  step: "步數", seconds: "已經過", secondsUnit: "秒", loss: "猜下一個音的誤差",
  lossNote: "曲線是訓練時的誤差；虛線是 5-gram 在驗證資料上的成績（1.46），拿來和每個片段旁邊的驗證誤差比。",
  autoplay: "有新片段就自動播放",
  snapshots: "它在這些時刻即興了一段",
  snapshotAt: (step: number) => `第 ${step} 步`,
  play: "播放", playing: "播放中", stopPlay: "停止播放",
  timbre: "音色", timbres: { pad: "溫暖墊音", epiano: "柔和電鋼琴", flute: "長笛" },
  roll: (step: number) => `第 ${step} 步寫的六小節：一條線是一個聲部，由上到下是女高音、女低音、男高音、男低音`,
  voices: ["女高音", "女低音", "男高音", "男低音"],
  inKey: "在調上", crossings: "聲部交錯", held: "拖長的音", parallels: "平行五度", copied: "最長抄襲",
  per100: "次／百格", eighths: "格",
  val: "驗證誤差",
  waiting: "按「開始訓練」，第 0 步的亂彈會出現在這裡。",

  stopTrain: "停止訓練",
  eta: "大約還要",
  metricsNote: "一格＝一個八分音符，八格是一小節。驗證誤差是它猜下一個音的平均誤差，越低越好，5-gram 的成績是 1.46。",
  rollPlain: "四個聲部的樂譜，由上到下是女高音、女低音、男高音、男低音",
  isNew: "新",
  judgeHint: "大約選 20 次就聽得出差別；選太多次它會只剩持續音。",
  judgeListen: "聽它現在寫的",
  judgeReset: "從頭開始",
  blindNeedAll: "三段都猜完才能對答案",
  blindWaiting: "聽完三段，再猜誰是誰",
  blindStart: "出三段給我聽",
  blindHow: "三段各四小節，一段是巴赫本人、一段是練好 1000 步的 AI、一段是五行數學規則，順序是隨機的。聽完再猜。",
  blindGuess: "你覺得這段是誰寫的",
  blindWho: { bach: "巴赫", ai: "AI", rules: "數學規則" },
  blindFavourite: "最喜歡這段",
  blindReveal: "對答案",
  blindAgain: "換三段",
  blindScore: (right: number) => `猜對 ${right} / 3`,
  blindYours: "你最喜歡的是",
  blindCorrect: "猜對", blindWrong: "猜錯", blindAnswer: "答案",
  blindChords: "和弦種類",
  judgeStart: "載入一個練好的作曲家", judgeLoading: "下載模型中…", judgeReady: "它寫了兩段，聽完選你比較喜歡的",
  pick: "選這段", candidate: (i: number): string => (i === 0 ? "A 段" : "B 段"),
  choices: (n: number) => `你已經選了 ${n} 次`,
  since: "從你開始選到現在",
  thinking: "它正在照你的選擇改自己…",
  judgeNote: "每選一次，模型往你選的那段靠近一點、離另一段遠一點（DPO）。它同時被拉在原本的樣子附近，不會一下子跑太遠。",
  before: "調教前", now: "現在",
};

const en: typeof zh = {
  train: "Start training", again: "Train again", stop: "Stop",
  trainNote: "Trained from scratch in your browser, in about three minutes. Listen as it learns, or keep reading.",
  loading: "Downloading 333 chorales…", failed: "The data failed to load. Reload the page to try again.",
  step: "Step", seconds: "Elapsed", secondsUnit: "s", loss: "Error guessing the next note",
  lossNote: "The curve is the training error; the dashed line is a 5-gram's validation score (1.46), to compare with each snapshot's validation error.",
  autoplay: "Play each new snapshot",
  snapshots: "It improvised at these moments",
  snapshotAt: (step: number) => `Step ${step}`,
  play: "Play", playing: "Playing", stopPlay: "Stop",
  timbre: "Sound", timbres: { pad: "Warm pad", epiano: "Soft e-piano", flute: "Flute" },
  roll: (step: number) => `Six bars written at step ${step}: one line per voice, soprano, alto, tenor and bass from the top`,
  voices: ["Soprano", "Alto", "Tenor", "Bass"],
  inKey: "In key", crossings: "Voices crossing", held: "Held notes", parallels: "Parallel fifths", copied: "Longest copy",
  per100: "/100 steps", eighths: "steps",
  val: "Validation error",
  waiting: "Press Start training: step 0's noodling will appear here.",

  stopTrain: "Stop training",
  eta: "About",
  metricsNote: "One step is an eighth note; eight of them make a bar. The validation error is how well it guesses the next note, lower is better; a 5-gram gets 1.46.",
  rollPlain: "A score for four voices: soprano, alto, tenor and bass from the top",
  isNew: "new",
  judgeHint: "About 20 picks is enough to hear the difference; many more and it holds every note.",
  judgeListen: "Hear what it writes now",
  judgeReset: "Start over",
  blindNeedAll: "Guess all three to see the answers",
  blindWaiting: "Listen to all three, then guess",
  blindStart: "Give me three pieces",
  blindHow: "Four bars each: one by Bach, one by the AI trained for 1,000 steps, one by the five lines of maths, in a random order. Listen first, then guess.",
  blindGuess: "Who wrote this one?",
  blindWho: { bach: "Bach", ai: "The AI", rules: "The maths" },
  blindFavourite: "My favourite",
  blindReveal: "Show the answers",
  blindAgain: "Three more",
  blindScore: (right: number) => `${right} of 3 right`,
  blindYours: "You liked",
  blindCorrect: "right", blindWrong: "wrong", blindAnswer: "Answer",
  blindChords: "Distinct chords",
  judgeStart: "Load a trained composer", judgeLoading: "Downloading the model…", judgeReady: "It wrote two pieces. Listen, then pick the one you like",
  pick: "Pick this one", candidate: (i: number) => (i === 0 ? "A" : "B"),
  choices: (n: number) => `${n} picks so far`,
  since: "Since your first pick",
  thinking: "Changing itself to match your pick…",
  judgeNote: "Each pick moves the model a little toward the piece you chose and away from the other (DPO), while a leash keeps it near where it started.",
  before: "Before", now: "Now",
};

export const useLabels = () => useLocaleLabels(zh, en);
