"use client";

import { usePathname } from "next/navigation";

const zh = {
  real: "真實世界（車子看不到這一邊）",
  believed: "車子自己畫的地圖",
  autopilot: "自動駕駛",
  stopAutopilot: "我自己開",
  reset: "重來",
  stick: "搖桿：往上是前進，往下是後退，左右是轉彎",
  driveHint: "拖曳搖桿開車；或先點一下搖桿，再用方向鍵／WASD。放開就停。",
  error: "位置誤差",
  wheelsOnly: "只靠輪子的話",
  closures: "認出舊地方",
  times: "次",
  lastFix: "上一次修正",
  metres: "m",
  full: "這張地圖記滿了（車子每半公尺記一筆，最多 320 筆）。",
  legendSlam: "車子估的路徑", legendWheels: "只靠輪子算的路徑", legendLoop: "認出舊地方時拉上的線",
  drift: "輪子有多不準",
  driftUnit: "rad/m",
  truePath: "真正走的路", wheelPath: "輪子以為的路",
  endError: "兩圈後差了",
  replay: "再跑一次",
  place: "地點", corner: "轉角", corridor: "走廊中段",
  dragHint: "拖曳青色的掃描去對白色的掃描；滑桿可以轉它。",
  rotate: "轉動",
  runIcp: "交給 ICP",
  scramble: "打亂",
  iteration: "第幾步", fit: "平均離牆", matched: "對上的點", off: "離正確答案",
  unsure: "粉紅色的橢圓：ICP 自己評估的「我在這個方向不確定」，放大 100 倍畫出來",
  addLoop: "加上閉環", pass: "第幾輪", tension: "彈簧的總張力", worst: "最歪的一點差了",
  springsHint: "每一段灰線是一根彈簧：「我覺得我從這裡到那裡走了這麼多」。紫色那根是「我回到起點了」。",
  loopClosure: "認得舊地方（閉環）",
  camera: "給它一台相機",
  wrong: "故意接錯一條",
  wronged: "已經接錯了",
  wrongNeeds: "先開一段路",
  cloudPlay: "開始", cloudPause: "暫停",
  cloudDrift: "只靠點雲比對，漂了", cloudPer: "每一圈的比對", cloudSweeps: "圈", ms: "ms",
  cloudLoad: "載入 3D 畫面",
  cloudLegend: "白：已經對齊的舊點雲。青：現在這一圈。青線：估計的路徑；粉紅線：真正的路徑。",
  degrees: "°",
};

const en: typeof zh = {
  real: "The real world (the car never sees this side)",
  believed: "The map the car is drawing",
  autopilot: "Autopilot",
  stopAutopilot: "Let me drive",
  reset: "Start over",
  stick: "Stick: up is forward, down is reverse, left and right turn",
  driveHint: "Drag the stick to drive, or click it and use the arrow keys / WASD. Let go to stop.",
  error: "position error",
  wheelsOnly: "on wheels alone",
  closures: "places recognised",
  times: "",
  lastFix: "last correction",
  metres: "m",
  full: "This map is full: the car remembers a scan every half metre, 320 at most.",
  legendSlam: "the car's estimate", legendWheels: "wheels alone", legendLoop: "links drawn when a place is recognised",
  drift: "how wrong the wheels are",
  driftUnit: "rad/m",
  truePath: "the path really driven", wheelPath: "the path the wheels report",
  endError: "off after two laps",
  replay: "Run again",
  place: "place", corner: "a corner", corridor: "mid-corridor",
  dragHint: "Drag the cyan scan onto the white one; the slider turns it.",
  rotate: "turn",
  runIcp: "Let ICP do it",
  scramble: "Scramble",
  iteration: "step", fit: "mean distance to wall", matched: "points matched", off: "off the right answer",
  unsure: "The pink ellipse is ICP's own estimate of where it is unsure, drawn 100× larger",
  addLoop: "Close the loop", pass: "pass", tension: "total spring tension", worst: "worst point is off by",
  springsHint: "Each grey link is a spring: \"I believe I moved this much from here to there.\" The violet one says \"I am back at the start.\"",
  loopClosure: "Recognise places (loop closure)",
  camera: "Give it a camera",
  wrong: "Close one loop wrongly",
  wronged: "Wrong link added",
  wrongNeeds: "Drive a bit first",
  cloudPlay: "Start", cloudPause: "Pause",
  cloudDrift: "drift from cloud matching alone", cloudPer: "matching per sweep", cloudSweeps: "sweeps", ms: "ms",
  cloudLoad: "Load the 3-D view",
  cloudLegend: "White: earlier sweeps, already aligned. Cyan: the current sweep. Cyan line: estimated path; pink line: the true path.",
  degrees: "°",
};

export function useLabels() {
  return usePathname()?.startsWith("/en") ? en : zh;
}
