"use client";

import { useLocaleLabels } from "@/components/lab/use-locale-labels";

const zh = {
  real: "真實世界（車子看不到這一邊）",
  believed: "車子自己畫的地圖",
  autopilot: "自動駕駛",
  stopAutopilot: "我自己開",
  reset: "重來",
  stick: "搖桿：往上是前進，往下是後退，左右是轉彎",
  driveHint: "拖曳搖桿開車；或先點一下搖桿，再用方向鍵／WASD。放開就停。",
  error: "位置誤差",
  wheelsOnly: "只靠輪子的話",
  closures: "認出舊地方",
  times: "次",
  lastFix: "上一次修正",
  metres: "m",
  full: "這張地圖記滿了（車子每半公尺記一筆，最多 320 筆）。",
  legendSlam: "車子估的路徑", legendWheels: "只靠輪子算的路徑", legendLoop: "認出舊地方時拉上的線",
  drift: "輪子有多不準",
  driftUnit: "rad/m",
  truePath: "真正走的路", wheelPath: "輪子以為的路",
  endError: "兩圈後差了",
  replay: "再跑一次",
  place: "地點", corner: "轉角", corridor: "走廊中段",
  dragHint: "拖曳青色的掃描去對白色的掃描（或先點一下畫面，用方向鍵移動）；滑桿可以轉它。",
  keysHint: "。方向鍵移動掃描，按住 Shift 移得更快",
  rotate: "轉動",
  runIcp: "交給 ICP",
  scramble: "打亂",
  iteration: "第幾步", fit: "平均離牆", matched: "對上的點", off: "離正確答案",
  unsure: "粉紅色的橢圓：ICP 自己評估的「我在這個方向不確定」，放大 100 倍畫出來",
  addLoop: "加上閉環", pass: "第幾輪", tension: "彈簧的總張力", worst: "最歪的一點差了",
  springsHint: "每一段灰線是一根彈簧：「我覺得我從這裡到那裡走了這麼多」。紫色那根是「我回到起點了」。",
  fastForward: "快轉中 ×4，快回到起點時會慢下來",
  backToNormal: "恢復正常",
  cards: { healthy: "正常", noClosure: "不認舊地方", drift: "輪子很不準", camera: "輪子很不準，但有相機", wrong: "認錯一次" } as Record<string, string>,
  computing: "計算中…",
  tryAbove: "用上面那台車試",
  tryShort: "試試",
  // What each picture shows, for readers who cannot see it; the numbers beside it carry the rest.
  picDrive: "3D 畫面，左邊是走廊裡的車和它的光達掃描，右邊是車子邊開邊畫出來的地圖與路徑",
  picWheels: "3D 畫面：車子真正走的路，和只靠輪子推算、越走越歪的路",
  picAlign: "3D 畫面：兩次光達掃描，其中一次可以拖曳去對齊另一次",
  picSprings: "3D 畫面：一串位姿用彈簧連起來，加上閉環後整條路徑被拉回原位",
  picOutcomes: "四張 3D 小圖，同一圈路在四種設定下各自畫出的地圖",
  picCloud: "3D 點雲：光達一圈一圈掃出的房間，和估計路徑、真實路徑兩條線",
  cardsNote: "同一條路線繞兩圈之後，車子畫出來的地圖。數字是最後的位置誤差。這四張圖是你的瀏覽器剛剛算出來的，沒有預先錄好。",
  cloudPlay: "開始", cloudPause: "暫停",
  cloudDrift: "只靠點雲比對，漂了", cloudPer: "每一圈的比對", cloudSweeps: "圈", ms: "ms",
  cloudLoad: "載入 3D 畫面",
  cloudLegend: "白：已經對齊的舊點雲。青：現在這一圈。青線：估計的路徑；粉紅線：真正的路徑。",
  degrees: "°",
};

const en: typeof zh = {
  real: "The real world (the car never sees this side)",
  believed: "The map the car is drawing",
  autopilot: "Autopilot",
  stopAutopilot: "Let me drive",
  reset: "Start over",
  stick: "Stick: up is forward, down is reverse, left and right turn",
  driveHint: "Drag the stick to drive, or click it and use the arrow keys / WASD. Let go to stop.",
  error: "position error",
  wheelsOnly: "on wheels alone",
  closures: "places recognised",
  times: "",
  lastFix: "last correction",
  metres: "m",
  full: "This map is full: the car remembers a scan every half metre, 320 at most.",
  legendSlam: "the car's estimate", legendWheels: "wheels alone", legendLoop: "links drawn when a place is recognised",
  drift: "how wrong the wheels are",
  driftUnit: "rad/m",
  truePath: "the path really driven", wheelPath: "the path the wheels report",
  endError: "off after two laps",
  replay: "Run again",
  place: "place", corner: "a corner", corridor: "mid-corridor",
  dragHint: "Drag the cyan scan onto the white one (or click the picture and use the arrow keys); the slider turns it.",
  keysHint: ". Arrow keys move the scan; hold Shift for bigger steps",
  rotate: "turn",
  runIcp: "Let ICP do it",
  scramble: "Scramble",
  iteration: "step", fit: "mean distance to wall", matched: "points matched", off: "off the right answer",
  unsure: "The pink ellipse is ICP's own estimate of where it is unsure, drawn 100× larger",
  addLoop: "Close the loop", pass: "pass", tension: "total spring tension", worst: "worst point is off by",
  springsHint: "Each grey link is a spring: \"I believe I moved this much from here to there.\" The violet one says \"I am back at the start.\"",
  fastForward: "Fast-forward ×4; it slows down as it nears the start",
  backToNormal: "Back to normal",
  cards: { healthy: "normal", noClosure: "never recognises a place", drift: "very wrong wheels", camera: "very wrong wheels, plus a camera", wrong: "one wrong recognition" } as Record<string, string>,
  computing: "working…",
  tryAbove: "Try it on the car above",
  tryShort: "Try it",
  picDrive: "3D view: on the left the car in its corridor with its lidar scan, on the right the map and path the car is drawing as it drives",
  picWheels: "3D view: the path the car really took, and the path worked out from the wheels alone, drifting further off",
  picAlign: "3D view: two lidar scans; one of them can be dragged to line up with the other",
  picSprings: "3D view: a chain of poses joined by springs; adding the loop closure pulls the whole path back into place",
  picOutcomes: "Four small 3D views: the map the same lap produces under four different settings",
  picCloud: "3D point cloud: the room as swept by the lidar turn after turn, with the estimated and the true path as two lines",
  cardsNote: "The map the car ends up with after the same two laps. The number is its final position error. Your browser worked these four out just now; nothing is pre-recorded.",
  cloudPlay: "Start", cloudPause: "Pause",
  cloudDrift: "drift from cloud matching alone", cloudPer: "matching per sweep", cloudSweeps: "sweeps", ms: "ms",
  cloudLoad: "Load the 3-D view",
  cloudLegend: "White: earlier sweeps, already aligned. Cyan: the current sweep. Cyan line: estimated path; pink line: the true path.",
  degrees: "°",
};

export function useLabels() {
  return useLocaleLabels(zh, en);
}
