"use client";

import { useLocaleLabels } from "@/components/lab/use-locale-labels";
import type { ShapeName } from "./shapes";

const zh = {
  fruit: { apple: "蘋果", banana: "香蕉", watermelon: "西瓜", strawberry: "草莓", cherries: "櫻桃", pear: "西洋梨" } satisfies Record<ShapeName, string>,
  left: "左邊長成",
  right: "右邊長成",
  train: "開始訓練",
  pause: "暫停",
  resume: "繼續",
  reset: "忘光重來",
  again: "重新取樣",
  steps: "訓練步數",
  loss: "誤差",
  perSec: "步／秒",
  blend: "混合的那一團：要幾分像左邊、幾分像右邊",
  blendName: (a: string, b: string, t: number) => (t === 0 ? a : t === 1 ? b : `${a} × ${b}`),
  blendValue: (a: string, b: string, t: number) => `${Math.round((1 - t) * 100)}% ${a} ＋ ${Math.round(t * 100)}% ${b}`,
  untrained: "還沒訓練。現在它對水果一無所知，所以雜訊走完 40 步還是一團雜訊。",
  learning: "正在學。每一輪都從全新的雜訊開始，走 40 步。",
  paused: "訓練暫停了，但取樣還在繼續：每一輪用的是同一個模型、不同的雜訊，所以每次長出來的點都不一樣。",
  stage: "三團點雲：左邊和右邊各是一種水果，中間是兩者的混合",
  level: "雜訊等級",
  levelValue: (t: number, total: number, kept: number) => `${t} / ${total}，原本的形狀還剩 ${kept}%`,
  noiseStage: "一顆水果的點雲，依照滑桿加上雜訊",
  sample: "從新的雜訊取樣一次",
  step: "第幾步",
  stepValue: (k: number, total: number, level: number) => `${k} / ${total}（雜訊等級 ${level}）`,
  stepsStage: "取樣過程中的點雲，拖動滑桿前後看",
  stepCount: "總共走幾步",
  show: "畫面上顯示",
  showPoints: "點現在的位置",
  showGuess: "模型此刻猜的成品",
  guessHint: (level: number): string => (level > 60 ? "雜訊還很大：它猜的是「所有可能答案的平均」，所以是一團平均顏色的糊球，不是水果。這是正確的。" : level > 20 ? "雜訊變小了，可能的答案範圍變窄，猜測開始有形狀。" : "雜訊很小了，它猜的成品和點現在的位置幾乎一樣。"),
  fieldStage: (fruit: string) => `${fruit}的一個垂直切面，每個格點上的箭頭是模型會把那裡的點往哪邊推`,
  fieldUntrained: "上面的模型還沒訓練過，所以箭頭是亂指的。訓練之後回來看，它們會轉向水果。",
  guidance: "引導強度：多聽「要哪一種水果」的話",
  guidanceValue: (w: number) => (w === 0 ? "0（完全不管要哪一種）" : w === 1 ? "1（照訓練時的樣子）" : w.toFixed(1)),
  guidanceStage: "兩種水果的點雲，用滑桿上的引導強度取樣",
  needTraining: "上面的模型還沒訓練過，所以這裡怎麼走都是一團雜訊。先回去按「開始訓練」，再回來按一次取樣。",
  trainedFor: (n: number) => `用的是上面那個模型，它目前訓練了 ${n.toLocaleString()} 步。`,
};

const en: typeof zh = {
  fruit: { apple: "apple", banana: "banana", watermelon: "watermelon", strawberry: "strawberry", cherries: "cherries", pear: "pear" },
  left: "On the left, grow",
  right: "On the right, grow",
  train: "Train",
  pause: "Pause",
  resume: "Resume",
  reset: "Forget everything",
  again: "Sample again",
  steps: "training steps",
  loss: "error",
  perSec: "steps/s",
  blend: "The blended cloud: how much like the left, how much like the right",
  blendName: (a: string, b: string, t: number) => (t === 0 ? a : t === 1 ? b : `${a} × ${b}`),
  blendValue: (a: string, b: string, t: number) => `${Math.round((1 - t) * 100)}% ${a} + ${Math.round(t * 100)}% ${b}`,
  untrained: "Not trained yet. It knows nothing about fruit, so after 40 steps the noise is still noise.",
  learning: "Learning. Every round starts from fresh noise and takes 40 steps.",
  paused: "Training is paused but sampling goes on: the same model, different noise each round, so the points never land in the same places twice.",
  stage: "Three point clouds: a fruit on the left, a fruit on the right, a blend of the two in the middle",
  level: "noise level",
  levelValue: (t: number, total: number, kept: number) => `${t} / ${total}, ${kept}% of the original shape left`,
  noiseStage: "A fruit's point cloud with as much noise added as the slider says",
  sample: "Sample once from fresh noise",
  step: "step",
  stepValue: (k: number, total: number, level: number) => `${k} / ${total} (noise level ${level})`,
  stepsStage: "The point cloud during sampling; drag the slider back and forth",
  stepCount: "steps in total",
  show: "show",
  showPoints: "where the points are",
  showGuess: "the model's guess of the result",
  guessHint: (level: number): string => (level > 60 ? "Still very noisy: its guess is the average of every possible answer, so it is a blob of average colour, not a fruit. That is correct." : level > 20 ? "Less noise, fewer possible answers: the guess is taking shape." : "Hardly any noise left: the guess and the points are almost the same."),
  fieldStage: (fruit: string) => `A vertical slice through the ${fruit}; the arrow at each grid point is where the model would push a point standing there`,
  fieldUntrained: "The model above has not been trained, so the arrows point anywhere. Train it and come back: they will turn towards the fruit.",
  guidance: "guidance: how hard to listen to \"which fruit\"",
  guidanceValue: (w: number) => (w === 0 ? "0 (ignores which fruit)" : w === 1 ? "1 (as trained)" : w.toFixed(1)),
  guidanceStage: "Point clouds of the two fruit, sampled with the guidance strength on the slider",
  needTraining: "The model above has not been trained, so whatever happens here stays noise. Go back, press Train, then sample again here.",
  trainedFor: (n: number) => `This uses the model above, trained for ${n.toLocaleString()} steps so far.`,
};

export function useLabels() {
  return useLocaleLabels(zh, en);
}
