"use client";

import { useLocaleLabels } from "@/components/lab/use-locale-labels";

const zh = {
  bench: "工作台的 3D 視圖：拖紅色方塊移動它，拖空白處轉視角",
  benchHint: "拖紅色方塊 · 拖空白處轉視角",
  eye: "頭部相機看到的 32 × 32 畫面",
  eyeNow: "頭部相機 32×32 · 每步重看",
  eyeOnce: "頭部相機 · 只看過這一張",
  dots: "彩色點是網路壓出來的 8 個關鍵點。",
  loading: "載入模型中…",
  failed: "模型載入失敗，重新整理再試一次。",
  policy: "誰在操作",
  closed: "持續看",
  open: "看一眼",
  play: "播放", pause: "暫停", reset: "重來",
  gap: "手離方塊", status: "狀態",
  there: "到了", going: "前往中", homing: "回原位拍照",
  pitch: "下傾", yaw: "左右轉", noise: "雜訊", light: "光線",
  cameraGroup: "撞歪頭部相機", pictureGroup: "弄髒畫面",
  pickBench: "工作台的 3D 視圖：拖紅色方塊或綠色目標墊移動它們，拖空白處轉視角",
  pickHint: "拖紅色方塊或綠色目標墊 · 拖空白處轉視角",
  pickShaken: "持續看＋晃過相機", pickFixed: "持續看", pickEye: "頭部相機看到的 48 × 48 畫面",
  pickEyeNow: "頭部相機 48×48 · 每步重看", pickEyeOnce: "頭部相機 · 只看過這一張",
  pickFetch: "去拿方塊", pickCarry: "搬去目標", pickPlaced: "放好了", pickShuffle: "換一個擺法",
  pickCount: (n: number) => `放好 ${n} 次`,
  kpFixed: "訓練時相機沒動過", kpShaken: "訓練時相機被晃過", kpShuffle: "換一個場景",
  offsetView: "從上往下看的工作台：紅色是方塊真正的位置，粉紅虛線是算出來的位置",
  offsetMean: "九個位置平均差", offsetNote: "差 3 公分以上就碰不到方塊。這裡沒有任何學習，只有幾何：計算是完美的，錯的只是它以為相機還在原位。",

  train: "開始訓練", again: "重新訓練", stop: "停止",
  trainNote: "在你的瀏覽器裡、用 JavaScript 從零訓練。訓練期間可以繼續往下讀。",
  step: "步數", seconds: "已經過", eta: "大約還要", loss: "動作的誤差",
  probe: "固定的一張畫面：看 8 個關鍵點怎麼慢慢找到手和方塊",
  testing: "訓練完成，測驗中…",
  result: "測驗結果",
  straight: "相機沒動", pitched: "相機下傾 5°",
  episodes: (n: number) => `各 ${n} 回合`,
  trialTitle: "現在換你弄歪它", trialLabel: "你練的模型正在找方塊（每一步都重看）",
  trialCount: (reached: number, tried: number) => `到了 ${reached} 次 / 試了 ${tried} 次`,
  secondsUnit: "秒",
};

const en: typeof zh = {
  bench: "The bench in 3D: drag the red block to move it, drag anywhere else to turn the view",
  benchHint: "drag the red block · drag elsewhere to turn",
  eye: "The head camera's 32 × 32 picture",
  eyeNow: "Head camera 32×32 · every step",
  eyeOnce: "Head camera · its only look",
  dots: "The coloured dots are the eight keypoints the network squeezes the picture into.",
  loading: "Loading the models…",
  failed: "The models failed to load. Reload the page to try again.",
  policy: "Driving",
  closed: "Keep looking",
  open: "Look once",
  play: "Play", pause: "Pause", reset: "Reset",
  gap: "Hand to block", status: "Status",
  there: "There", going: "On its way", homing: "Going home to look",
  pitch: "Tilt", yaw: "Turn", noise: "Noise", light: "Light",
  cameraGroup: "Knock the head camera", pictureGroup: "Spoil the picture",
  pickBench: "The bench in 3D: drag the red block or the green pad to move them, drag anywhere else to turn the view",
  pickHint: "drag the red block or the green pad · drag elsewhere to turn",
  pickShaken: "Keep looking + shaken camera", pickFixed: "Keep looking", pickEye: "The head camera's 48 × 48 picture",
  pickEyeNow: "Head camera 48×48 · every step", pickEyeOnce: "Head camera · its only look",
  pickFetch: "Fetching the block", pickCarry: "Carrying it to the pad", pickPlaced: "Placed", pickShuffle: "Another layout",
  pickCount: (n: number) => `${n} placed`,
  kpFixed: "Camera never moved in training", kpShaken: "Camera shaken in training", kpShuffle: "Another scene",
  offsetView: "The bench from above: red is where each block is, dashed pink is where the calculation puts it",
  offsetMean: "Mean error, nine places", offsetNote: "More than 3 cm off misses the block. Nothing is learned here, it is geometry: the calculation is perfect and only its belief about the camera is stale.",

  train: "Start training", again: "Train again", stop: "Stop",
  trainNote: "Trained from scratch in your browser, in JavaScript. Keep reading while it runs.",
  step: "Step", seconds: "Elapsed", eta: "About", loss: "Action error",
  probe: "One fixed picture: watch the eight keypoints find the hand and the block",
  testing: "Trained. Testing…",
  result: "Test",
  straight: "Camera as trained", pitched: "Camera tilted 5°",
  episodes: (n: number) => `${n} episodes each`,
  trialTitle: "Now knock its camera", trialLabel: "Your model, finding blocks (it looks again every step)",
  trialCount: (reached: number, tried: number) => `${reached} reached of ${tried} tried`,
  secondsUnit: "s",
};

export const useLabels = () => useLocaleLabels(zh, en);
